import { Injectable } from '@angular/core';
import { FlattenedShape } from './svg-flattener.service';

export interface GcodeParams {
  targetWidthMm: number;
  feedRateMmMin: number;
  laserPower: number;
  passes: number;
}

@Injectable({ providedIn: 'root' })
export class GcodeGeneratorService {
  /**
   * Turns flattened SVG shapes into laser G-code: G0 travel to each shape's start,
   * M4 (dynamic laser power, avoids corner burn) for the cut, G1 moves at the feed rate,
   * M5 to turn the laser off before travelling to the next shape.
   */
  generate(
    shapes: FlattenedShape[],
    svgWidth: number,
    svgHeight: number,
    params: GcodeParams,
  ): string {
    if (shapes.length === 0) {
      throw new Error('No cuttable shape found in this SVG.');
    }

    const scale = svgWidth > 0 ? params.targetWidthMm / svgWidth : 1;
    const toMachine = (point: { x: number; y: number }) => ({
      x: point.x * scale,
      y: (svgHeight - point.y) * scale,
    });
    const format = (value: number) => value.toFixed(3);

    const lines: string[] = [
      '; Generated by WebCutter',
      `; ${shapes.length} shape(s), target width ${params.targetWidthMm} mm, ${params.passes} pass(es)`,
      'G21 ; units in millimeters',
      'G90 ; absolute positioning',
      'M5 ; laser off',
    ];

    for (let pass = 1; pass <= params.passes; pass++) {
      lines.push(`; Pass ${pass}/${params.passes}`);
      for (const shape of shapes) {
        const [start, ...rest] = shape.points.map(toMachine);
        if (!start || rest.length === 0) {
          continue;
        }
        lines.push(`G0 X${format(start.x)} Y${format(start.y)}`);
        lines.push(`M4 S${params.laserPower}`);
        for (const point of rest) {
          lines.push(`G1 X${format(point.x)} Y${format(point.y)} F${params.feedRateMmMin}`);
        }
        lines.push('M5');
      }
    }

    lines.push('G0 X0 Y0 ; return to origin');
    lines.push('M30 ; end of program');

    return lines.join('\n');
  }
}
